server:
  port: 80

spring:
  profiles:
    include: oauth

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: bd67c51fea3cc6558dbcda8c545c702a
            client-secret: 5gQnrVFNLNqRHH7lMmnoFyVkAj6uB0Vk
            redirect-uri: http://localhost/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          google:
            client-id: 456558181029-i5aq4v6j1c03ap0psfdgestaukh2f6ue.apps.googleusercontent.com
            client-secret: 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
            scope: email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  devtools:
    livereload:
      enabled: true

  datasource:
    url: jdbc:mariadb://localhost:3306/adam
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: a12345678

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      location: /Users/user/Documents/data
      max-file-size: 10MB

com:
  kakao:
    upload:
      path: /Users/user/Documents/data

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        security: trace