server:
  port: 80

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: a12345678
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      location: C:/Users/user/Documents/StudyDirectory/data
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

com:
  adamsoft:
    upload:
      path: C:/Users/user/Documents/StudyDirectory/data